export const PATH = {
  HOME: '/',
  SEARCH: '/search',
  MESSAGE: '/message',
  BOOKMARK: '/bookmark',
  SETTINGS: '/settings',
  SETTINGS_PASSWORD: '/settings/password',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  UPLOAD: '/upload',
  FORGOT_PASSWORD: '/forgot-password',
  VERIFY_FORGOT_PASSWORD: '/verify-forgot-password',
  RESET_PASSWORD: '/reset-password',
  EXPLORE: '/explore',
  CONNECT: '/connect',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS_OF_SERVICE: '/terms-of-service',
  VERIFY_EMAIL: '/verify-email',
  NOT_FOUND: '/404',

  PROFILE: '/:user_id',
  FOLLOW: '/:user_id/follow',
  POST_DETAIL: '/post/:post_id',
  UPDATE_POST: '/update-post/:post_id',
  UPDATE_PROFILE: '/update-profile/:user_id'
}
